[package]
name = "pig"
authors = ["ğŸ‡«ğŸ‡· Romain TRUCHI"]
version = "0.1.0"
edition = "2021"
description = "ğŸ¦€ OpenAPI code generation ğŸ·"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
colored = "2.0.4"
notify = "6.1.1"
openapiv3 = "1.0.3"
serde = "1.0.188"
serde_json = "1.0.107"
serde_yaml = "0.9.25"
tera = "1.19.1"
thiserror = "1.0.48"
walkdir = "2.4.0"
